services:
  traefik:
    image: traefik:v3.1.2-windowsservercore-1809
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.file.directory=c:\\services"
      - "--providers.file.watch=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=test@test.com"
    volumes:
      - .\\services:c:/services

  backend_core:
    build: .
    container_name: backend_core
    expose:
      - 80

  backend_iis:
    build: ./IIS
    container_name: backend_iis
    expose:
      - 80
